AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Warning
    System: Warning
    Microsoft: Warning
eureka:
  client:
    serviceUrl: http://192.168.99.100:8761/eureka/
    validate_certificates: false
mysql:
  client:
    server: 192.168.99.100
    sslmode: none
management: 
  endpoints: 
    path: /cloudfoundryapplication
    cloudfoundry: 
      validateCertificates: false
